on: workflow_dispatch
name: Update prod branch on release
jobs:
  sync:
    name: Update nightly branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/master'
      with:
        branch: angerson-nightly
        force: 1 # To push-force to the branch
        githubToken: ${{ secrets.GITHUB_TOKEN }}
