on: workflow_dispatch
name: Mirror 'master' to 'nightly'
jobs:
  master-to-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: peterjgrainger/action-create-branch@v1.0.0
      name: Create 'nightly-final' branch if it doesn't already exist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'nightly-final'
    - uses: zofrex/mirror-branch@v1
      name: Set nightly-final to master HEAD
      with:
        target-branch: 'nightly-final'
